### ISSUE TITLE
Error: Target not found: build\favicon.ico\favicon.ico.page.js

### ISSUE THREAD

**Issue by Tanyusha** [bevis-ui/bevis-stub#8]
C:\your-project>node_modules\.bin\supervisor -w server,configs -- server/boot.js

		DEBUG: Running node-supervisor with
		DEBUG:   program 'server/boot.js'
		DEBUG:   --watch 'server,configs'
		DEBUG:   --ignore 'undefined'
		DEBUG:   --extensions 'node|js'
		DEBUG:   --exec 'node'

		DEBUG: Starting child process with 'node server/boot.js'
		DEBUG: Watching directory 'C:\your-project\server' for changes.
		DEBUG: Watching directory 'C:\your-project\configs' for changes.
		14:52:25 - info: worker 4024 started
		14:52:25 - info: app started on 8080
		14:52:25 - info: worker 7300 started
		14:52:25 - info: app started on 8080
		14:53:35.529 - [rebuild] [build\index\index.page.js - \build\index\index.sources] sources
		14:53:35.616 - [isValid] [build\index\index.page.js - \build\index\index.dest-deps.js] deps
		14:53:35.620 - [rebuild] [build\index\index.page.js - \build\index\index.files] files
		14:53:35.621 - [rebuild] [build\index\index.page.js - \build\index\index.dirs] files
		14:53:35.652 - [isValid] [build\index\index.page.js - \build\index\index.page.js] page-js
		14:53:35.714 - [rebuild] [build\index\index.bt.js - \build\index\index.sources] sources
		14:53:35.717 - [isValid] [build\index\index.bt.js - \build\index\index.dest-deps.js] deps
		14:53:35.719 - [rebuild] [build\index\index.bt.js - \build\index\index.files] files
		14:53:35.720 - [rebuild] [build\index\index.bt.js - \build\index\index.dirs] files
		14:53:35.740 - [isValid] [build\index\index.bt.js - \build\index\index.bt.js] bt-server
		14:53:35 - verbose: bt running
		14:53:35 - verbose: bt completed at 5 ms
		14:53:36.399 - [rebuild] [build\index\_index.css - \build\index\index.sources] sources
		14:53:36.412 - [isValid] [build\index\_index.css - \build\index\index.dest-deps.js] deps
		14:53:36.414 - [rebuild] [build\index\_index.css - \build\index\index.files] files
		14:53:36.415 - [rebuild] [build\index\_index.css - \build\index\index.dirs] files
		14:53:36.424 - [isValid] [build\index\_index.css - \build\index\index.css] css-stylus-with-autoprefixer
		14:53:36.599 - [rebuild] [build\index\_index.ru.js - \build\index\index.sources] sources
		14:53:36.604 - [isValid] [build\index\_index.ru.js - \build\index\index.dest-deps.js] deps
		14:53:36.605 - [rebuild] [build\index\_index.ru.js - \build\index\index.files] files
		14:53:36.623 - [rebuild] [build\index\_index.ru.js - \build\index\index.dirs] files
		14:53:36.653 - [isValid] [build\index\_index.ru.js - \build\index\index.bt.client.js] bt-client-module
		14:53:36.696 - [isValid] [build\index\_index.ru.js - \build\index\index.lang.ru.js] y-i18n-lang-js
		14:53:36.700 - [isValid] [build\index\_index.ru.js - \build\index\index.source.ru.js] js
		14:53:36.706 - [rebuild] [build\index\_index.css - \build\index\_index.css] file-copy
		14:53:36.771 - [isValid] [build\index\_index.ru.js - \build\index\index.modernizr.ru.js] modernizr-js
		14:53:36.855 - [isValid] [build\index\_index.ru.js - \build\index\index.ru.js] autopolyfiller
		14:53:36.966 - [rebuild] [build\index\_index.ru.js - \build\index\_index.ru.js] file-copy
		14:53:37 - error: Error: Target not found: build\favicon.ico\favicon.ico.page.js
			at Error (<anonymous>)
			at TargetNotFoundError (C:\your-project\node_modules\enb\lib\errors\target-not-found-error.js:11:23)
			at module.exports.inherit._resolveTarget (C:\your-project\node_modules\enb\lib\make.js:392:15)
			at C:\your-project\node_modules\enb\lib\make.js:409:36
			at Array.forEach (native)
			at module.exports.inherit._resolveTargets (C:\your-project\node_modules\enb\lib\make.js:408:21)
			at module.exports.inherit.buildTargets (C:\your-project\node_modules\enb\lib\make.js:442:35)
			at C:\your-project\node_modules\enb\lib\server\server-middleware.js:81:33
			at Array.0 (C:\your-project\node_modules\vow\lib\vow.js:194:56)
			at callFns (C:\your-project\node_modules\vow\lib\vow.js:452:35)

**Comment by makishvili** [comment]
Понял, исправлю.
