### ISSUE TITLE
Windows. Проблемы с кириллицей

### ISSUE THREAD

**Issue by Tanyusha** [bevis-ui/bevis-stub#9]
Если в пути к файлу встречаются символы кириллицы, происходит следующая ошибка: 

	C:\Users\Таника\bevis-stub>node_modules\.bin\enb make
	15:02:42.930 - build started
	15:03:12.564 - [rebuild] [build\index\index.sources] sources
	15:03:12.814 - [rebuild] [build\index\index.dest-deps.js] deps
	15:03:12.817 - [rebuild] [build\index\index.files] files
	15:03:12.817 - [rebuild] [build\index\index.dirs] files
	15:03:13.167 - [rebuild] [build\index\index.css] css-stylus-with-autoprefixer
	15:03:13.237 - [rebuild] [build\index\index.bt.js] bt-server
	15:03:13.243 - [rebuild] [build\index\index.page.js] page-js
	15:03:13.248 - [rebuild] [build\index\_index.css] file-copy
	15:03:13.343 - [rebuild] [build\index\index.bt.client.js] bt-client-module
	15:03:13.357 - [rebuild] [build\index\index.lang.ru.js] y-i18n-lang-js
	15:03:13.365 - [rebuild] [build\index\_index.lang.ru.js] file-copy
	15:03:13.483 - [failed] [build\index\index.source.ru.js] js
	15:03:13.485 - [failed] [build\index\index.modernizr.ru.js] modernizr-js
	15:03:13.485 - [failed] [build\index\index.ru.js] autopolyfiller
	15:03:13.486 - [failed] [build\index\_index.ru.js] file-copy
	15:03:13.487 - build failed
	SyntaxError: Unexpected number
		at Object.parse (native)
		at module.exports.getSourceMap (C:\Users\Таника\bevis-stub\node_modules\enb-bevis\node_modules\enb-source-map\lib\utils.js:11:22)
		at Object.File.writeFileFragment (C:\Users\Таника\bevis-stub\node_modules\enb-bevis\node_modules\enb-source-map\lib\file.js:42:28)
		at Object.File.writeFileContent (C:\Users\Таника\bevis-stub\node_modules\enb-bevis\node_modules\enb-source-map\lib\file.js:20:14)
		at C:\Users\Таника\bevis-stub\node_modules\enb-bevis\techs\js.js:66:22
		at Array.forEach (native)
		at null.<anonymous> (C:\Users\Таника\bevis-stub\node_modules\enb-bevis\techs\js.js:65:21)
		at Array.0 (C:\Users\Таника\bevis-stub\node_modules\enb-bevis\node_modules\vow\lib\vow.js:555:56)
		at Object.callFns [as _onImmediate] (C:\Users\Таника\bevis-stub\node_modules\enb-bevis\node_modules\vow\lib\vow.js:1148:35)
		at processImmediate [as _immediateCallback] (timers.js:354:15)
		
Перемещение проекта в другую директорию решит проблему.

**Comment by makishvili** [comment]
Таника, я не понял, что означает "перемещение проекта в другую директорию решит проблему". Вы не могли бы чуть подробнее описать, что вы разузнали об этой ошибке и её решении?

**Comment by Tanyusha** [comment]
При попытке запустить проект, возникла данная ошибка. 

В процессе работы с python мне неоднократно приходилось сталкиваться с проблемами декодирования, причиной которых были символы кириллицы.

Поскольку ошибка возникает в процессе работы с файлами, я решила, что это может быть связано с наличием unicode символов в пути к файлу. Я переместила проект в другую папку так, чтобы в пути символов кириллицы не встречалось, и это решило проблему.

**Comment by makishvili** [comment]
Теперь понял.

Я не уверен, что мы с этим можем что-то сделать. Даже не представляю, что и как.
Разве только явно написать, что в имени проекта не должно быть кириллицы? Как считаете, это стоит явно написать?

**Comment by Tanyusha** [comment]
Предлагаю следующие изменения: https://github.com/bevis-ui/bevis-stub/pull/10

**Comment by makishvili** [comment]
Спасибо :)
